version: '3.5'

services:
  postgres:
    container_name: postgres12
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: simple_bank
    volumes:
       - postgres:/data/postgres  
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin_simplebank
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge    

volumes:
    postgres:
      driver: local
    pgadmin:
      driver: local    